export interface Tool {
  id: string;
  name: string;
  language: 'javascript' | 'python' | 'powershell';
  content: string;
}

export interface TodoItem {
  id: string;
  text: string;
  status: 'Pending' | 'In Progress' | 'Completed';
}

export interface Step {
  id: string;
  unitId: string; // The ID of the unit to activate
}

export interface Scheduler {
  enabled: boolean;
  type: 'datetime' | 'interval';
  datetime?: string; // ISO 8601 format
  intervalValue?: number;
  intervalUnit?: 'minutes' | 'hours' | 'days';
}

export interface Room {
  id: string;
  name: string;
  manager?: string;
  units: Unit[];
  tools?: Tool[];
  stepMaker?: Step[];
}

export interface DataConnector {
  id:string;
  type: 'notion' | 'github';
  name: string;
  connected: boolean;
}

export interface TrainingSource {
  id: string;
  name: string;
  size: string;
  status: 'Queued' | 'Parsing' | 'Chunking' | 'Embedding' | 'Completed' | 'Error';
  neuronCount: number;
  message?: string;
}

export interface FileReference {
  id: string; // A unique ID for the file content in the central file store
  name: string;
  type: string;
}

export interface ExperienceNeuron {
  id: string;
  timestamp: string; // ISO 8601 format
  response: string; // The AI's response that was rated
  rf: 'up' | 'down';
  reason?: string; // User's or Arbiter's reason
  isSystemRf: boolean; // Was this generated by the RF Arbiter?
  adaptedDirective?: string; // A concrete rule learned from this experience
  files?: FileReference[]; // References to files associated with this experience
  imageAnalysis?: ImageMetadata;
  audioAnalysis?: AudioMetadata;
}

export interface Unit {
  id:string;
  name: string;
  type: 'Standard' | 'Manager' | 'RAG' | 'Code RAG' | 'Drive';
  purpose: string;
  isLoopOpen: boolean;
  todo: {
    items: TodoItem[];
  };
  todoVector: {
    provider: 'sqlite';
    path: string;
  };
  llmProvider: {
    provider: string; // ID of the LLM provider
    model: string;
    connectionId?: string; // For both cloud and local SERVER providers
  };
  prompt: string;
  trainingVector: {
    enabled: boolean;
    vectorStore: {
      provider: string; // ID of the vector DB provider
      connectionId?: string;
      path?: string; // For local-embedded vector stores like LanceDB
    };
    neurons: number;
    sources?: TrainingSource[];
  };
  experienceVector: {
    provider: string; // ID of the vector DB provider
    neurons: ExperienceNeuron[];
    connectionId?: string;
    path?: string; // For local-embedded vector stores like LanceDB
  };
  standardDb: {
    provider: string; // ID of the standard DB provider
    enabled: boolean;
    connectionId?: string;
    path?: string; // For local-embedded DBs like SQLite
  };
  scaleDb: {
    enabled: boolean;
    provider: string; // ID of the standard DB provider
    connectionId?: string;
    path?: string; // For local-embedded DBs like SQLite
    values: ScaleValue[];
  };
  ragBaseId?: string;
  tools: string[]; // Array of Tool IDs
  scheduler?: Scheduler;
}

export interface RAGBase {
  id: string;
  name: string;
  vectorStore: {
    provider: string;
    connectionId?: string;
    path?: string; // For local-embedded vector stores like LanceDB
  };
  chunking: {
    chunkSize: number;
    overlap: number;
  };
  retrieval: {
    topK: number;
  };
  reranker: {
    enabled: boolean;
    provider?: string;
    model?: string;
    connectionId?: string; // For both cloud and local SERVER providers
  };
  useTranscript: boolean;
  dataConnectors?: DataConnector[];
}

export interface ScaleValue {
    id: string;
    name: string;
    score: number;
    min: number;
    max: number;
    defaultValue: number;
}

export interface ChatFile {
  name: string;
  type: string; // MIME type
  content: string; // Base64 encoded content
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'ai';
  text: string;
  files?: ChatFile[];
  timestamp: string; // ISO 8601 format
  rf?: 'up' | 'down';
  rfReason?: string;
  systemRf?: boolean;
  isThinking?: boolean;
  participantUnitIds?: string[];
  imageAnalysis?: ImageMetadata;
  audioAnalysis?: AudioMetadata;
}

export interface AixDataPacket<T, M> {
  id: string;
  timestamp: string; // ISO 8601 format
  source: T;
  metadata: M;
}

export interface ImageMetadata {
  description?: string;
  guiElements?: { element: string; coordinates: [number, number, number, number]; }[];
  facialEmotions?: { faceId: number; emotion: string; confidence: number; }[];
  sceneRelationships?: string;
  backgroundContext?: string;
  lightingAndEffects?: string;
  imageGenerated?: boolean;
}

export interface ImagePacket extends AixDataPacket<string, ImageMetadata> {
  type: 'ImagePacket';
}

export interface AudioMetadata {
  transcription?: string;
  soundClasses?: { sound: string; confidence: number; }[];
  vadSegments?: { start: number; end: number; }[];
  ttsGenerated?: boolean;
  wordTimestamps?: { word: string; start: number; end: number; }[];
}

export interface AudioPacket extends AixDataPacket<string, AudioMetadata> {
  type: 'AudioPacket';
}

export interface ProviderOption {
    id: string;
    name: string;
}

export interface ModelOption extends ProviderOption {
    provider: 'local' | 'cloud';
}

export interface ApiKey {
  id: string;
  key: string;
  createdAt: string; // ISO 8601 format
}

export interface CloudConnection {
  id: string;
  name: string;
  providerId: string;
  key: string;
  url?: string; // For Supabase, Turso, etc.
  environment?: string; // For Pinecone, etc.
  createdAt: string; // ISO 8601 format
}

export interface LocalProviderConnection {
  id: string;
  name: string;
  providerId: string; // 'ollama', 'lmstudio', 'local-rerank-server'
  url: string;
  createdAt: string; // ISO 8601 format
}

export interface InputDevice {
  id: string;
  name: string;
}

export interface GlobalEmbeddingSettings {
    provider: string;
    model: string;
    connectionId?: string; // For both cloud and local SERVER providers
}

export interface ApiSettings {
  apiKeys: ApiKey[];
  cloudConnections: CloudConnection[];
  localProviderConnections: LocalProviderConnection[];
  globalEmbeddingSettings: GlobalEmbeddingSettings;
  apiPort: number;
  micId: string | null;
  speakerId: string | null;
  pushToTalkKey: string | null;
  webhookUrl: string | null;
  noiseSuppression: boolean;
  micGain: number;
  speakerGain: number;
}

export interface Model {
    id: string;
    name: string;
}

export interface Provider {
    id:string;
    name: string;
    type: 'cloud' | 'local' | 'local-embedded';
    models?: Model[];
    embeddingModels?: Model[];
}
